language: python
python:
  - "3.5"
  - "3.6"
cache: pip
before_cache: rm -f $HOME/.cache/pip/log/debug.log
install:
    - pip install "pytest>=5" .[test] codecov
script: pytest
after_success: codecov
